com.fasterxml.jackson.*:* = 2.20.1
com.fasterxml.jackson.core:jackson-annotations = 2.20
com.palantir.witchcraft.api:* = 2.6.0
com.google.guava:guava = 33.5.0-jre
org.immutables:* = 2.12.1
org.assertj:assertj-core = 3.27.6
org.junit.jupiter:* = 6.0.2
org.junit.platform:* = 6.0.2
org.junit.vintage:* = 6.0.2
org.mockito:* = 5.21.0
org.slf4j:* = 2.0.17
com.netflix.nebula:nebula-test = 10.6.2
com.palantir.gradle.idea-configuration:gradle-idea-configuration = 0.3.0
org.apache.commons:commons-text = 1.15.0

# test
com.palantir.conjure.java.runtime:* = 8.30.0
