com.fasterxml.jackson.*:* = 2.21.4
com.fasterxml.jackson.core:jackson-annotations = 2.21
com.palantir.witchcraft.api:* = 2.11.0
com.google.guava:guava = 33.6.0-jre
org.immutables:* = 2.12.2
org.assertj:assertj-core = 3.27.7
org.junit.jupiter:* = 6.1.2
org.junit.platform:* = 6.1.2
org.junit.vintage:* = 6.1.2
org.mockito:* = 5.23.0
org.slf4j:* = 2.0.17
com.netflix.nebula:nebula-test = 11.11.3
com.palantir.gradle.idea-configuration:gradle-idea-configuration = 0.8.0
org.apache.commons:commons-text = 1.15.0

# test
com.palantir.conjure.java.runtime:* = 8.39.0
