apply plugin: 'com.palantir.external-publish-intellij'

def minimumIntellijBuild = '232.10203.10'

repositories {
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdeaCommunity(minimumIntellijBuild) {
            useInstaller = false
        }
    }

    implementation project(':witchcraft-logging-formatting'), {
        exclude group: 'org.slf4j'
        because 'Must use intellij slf4j to produce logging'
    }
    implementation 'com.palantir.witchcraft.api:witchcraft-logging-api-objects', {
        exclude group: 'org.slf4j'
        because 'Must use intellij slf4j to produce logging'
    }
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8'

    annotationProcessor 'org.immutables:value'
    compileOnly 'org.immutables:value-annotations'

    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core'
}

intellijPlatform {
    projectName = 'witchcraft-logging-idea'
    pluginConfiguration {
        ideaVersion {
            sinceBuild = minimumIntellijBuild
            untilBuild = provider { null }
        }
    }
    pluginVerification {
        ides {
            create('IC', '2024.1')
            create('IU', '2024.2.1')
            create('GO', '2024.2')
        }
    }
}
