apply plugin: 'groovy'
apply plugin: 'java-gradle-plugin'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'com.palantir.gradle-plugin-testing'
apply plugin: 'com.palantir.external-publish-gradle-plugin'

dependencies {
    api gradleApi()
    implementation project(':witchcraft-logging-formatting')
    implementation 'com.google.guava:guava'
    implementation 'com.palantir.gradle.idea-configuration:gradle-idea-configuration'

    testImplementation gradleTestKit()
    testImplementation 'com.google.guava:guava'
    testImplementation 'com.netflix.nebula:nebula-test'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation 'org.junit.jupiter:junit-jupiter'

    testRuntimeOnly 'org.junit.vintage:junit-vintage-engine'
}

gradlePlugin {
    website = 'https://github.com/palantir/witchcraft-java-logging'
    vcsUrl = 'https://github.com/palantir/witchcraft-java-logging'

    plugins {
        witchcraftLoggingPlugin {
            displayName = 'Palantir Witchcraft Logging Plugin'
            id = 'com.palantir.witchcraft-logging'
            implementationClass = 'com.palantir.witchcraft.java.logging.gradle.WitchcraftLoggingPlugin'
            description = 'Palantir Witchcraft logging plugins used to improve developer experience building, running, and debugging applications using the witchcraft logging api: https://github.com/palantir/witchcraft-api.'
            tags.set(['witchcraft', 'logging', 'idea'])
        }
        witchcraftLoggingTestReportPlugin {
            displayName = 'Palantir Witchcraft Logging Test Report Rendering Plugin'
            id = 'com.palantir.witchcraft-logging-testreport'
            implementationClass = 'com.palantir.witchcraft.java.logging.gradle.testreport.TestReportFormattingPlugin'
            description = 'Palantir Witchcraft logging plugins used to improve developer experience building, running, and debugging applications using the witchcraft logging api: https://github.com/palantir/witchcraft-api.'
            tags.set(['witchcraft', 'logging', 'idea'])
        }
    }
}

test {
    systemProperty 'ignoreDeprecations', 'true'
}

gradleTestUtils {
    gradleVersions = ['8.14.3']
    configurationCacheEnabled = true
}
